apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    env: app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: app
  template:
    metadata:
      labels:
        env: app
    spec:
      containers:
        - name: api
          image: 829751303926.dkr.ecr.us-east-1.amazonaws.com/api:test
          ports:
            - containerPort: 80
